spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/my_blog
      username: root
      password: 123456
      max-active: 20
      initial-size: 1
      max-wait: 60000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      async-init: true

      #监控统计的stat,以及防sql注入的wall
      filters: stat,wall

      stat-view-servlet:
        #是否启用StatViewServlet默认值true
        enabled: true
        # 需要账号密码才能访问控制台，默认为root
        login-username: admin
        login-password: admin
        #访问路径为/druid时，跳转到StatViewServlet
        url-pattern: /druid/*
        #IP白名单
        allow: 127.0.0.1
        #&emsp;IP黑名单（共同存在时，deny优先于allow）
        deny:
      web-stat-filter:
        enabled: true
        url-pattern: /*
      aop-patterns: cn.zj.service.*

      useGlobalDataSourceStat: true
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
---
mybatis:
#  configuration:
#    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
  #pagehelper分页插件配置

---
jwt:
  header: jwtHeader   #jwt的请求头
  secret: eyJleHAiOjE1NDMyMDUyODUsInN1YiI6ImFkbWluIiwiY3Jl   #jwt的加密字符串
  expiration: 3600000   #jwt token有效时间（毫秒）
  route:
    login: /auth/login    #登录地址
    refresh: /auth/refresh  #刷新token地址
    register: /auth/register  #注册的地址
---
#uploadFile:
#  resourceHandler: /upload/**   #请求 url 中的资源映射
#  location: E:/home/upload/ #自定义上传文件本地保存路径
uploadFile:
  resourceHandler: /upload/**
  location: /home/upload/
